################# 적용할 Profile 선택##################
spring:
  profiles:
    active: local
###################################################

  http:
    encoding:
      charset: UTF-8

  info:
    build:
      encoding: UTF-8

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username:  # DB 계정
    password:  # DB 암호

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    #      generate_statistics: true
    #        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
#      max-file-size: 5MB
#      max-request-size: 15MB

  security:
    user:
      name: user
      password: test

  mail:
    host: # smtp 서버 host ip
    port: 25 # smtp 서버 port
    username: # 계정

server:
  tomcat:
    uri-encoding: UTF-8
    protocol-header: x-forwarded-proto
    protocol-header-https-value: https
    remote-ip-header: x-forwarded-for
  use-forward-headers: true
  port: 8081
  servlet:
    session:
      tracking-modes: cookie

# Hibernate SQL Query 출력(Log 삽입)
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

  # App Properties
sbdc:
  app:
    jwtSecret: # jwtSecret 키
#    jwtExpiration: 600000
#    jwtExpiration: 1800000
    jwtExpiration: 1800000
---
############################ Local Profile #############################
spring:
  profiles: local

  datasource:
    url: jdbc:sqlserver://127.0.0.1:14343;database=sbdc # DB 접속 url

sbdc:
  app:
    frontServerAPI: http://localhost:4200
    fileServer: # fileServer ip
    dataServer: 127.0.0.1 # dataServer ip

logging:
  file: ./log/local
---
############################## Dev Profile ##############################
spring:
  profiles: dev

  datasource:
    url: # DB 접속 url

sbdc:
  app:
    frontServerAPI: # front 서버 ip
    jwtSecret: # jwtSecret 키
    fileServer: # fileServer ip
    dataServer: # dataServer ip

logging:
  file: ./log/dev

---
############################ 운영 서버 Profile ############################
spring:
  profiles: prod

  datasource:
    url: # DB 접속 url

sbdc:
  app:
    frontServerAPI: # front 서버 ip
    jwtSecret: # jwtSecret 키
    fileServer: # fileServer ip
    dataServer: # dataServer ip

logging:
  file: ./log/prod